### PR TITLE
Service worker state fixes, Google Drive Permissions fixes

### LINKED ISSUE #338: Google drive error
I just installed Tusk on Windows 10, Chrome: 77.0.3865.90 (Official Build) (64-bit) (cohort: Stable). When I try to turn on Google Drive under the Manage Databases tab, there's no dialogue asking me to approve access to google drive. Instead, a red box appears beside it with the text [object Object].

I still have CKP installed but I can't see why that would interfere with this issue or cause it. Happy to provide more details.

### LINKED ISSUE #349: Slide to remain logged in until browser exits stopped working
### Steps to reproduce - current behaviour

I cannot really put my finger on it, but it used to be the case that Tusk remained logged in to the vault when you set the slider to 'Until browser exits', this does not seem to work anymore, I have to log in multiple times now, he remembers the session for a short while and then requires a new login.

### What is the expected behaviour
The slider controls the time until next login is required

#### Environment 
OS: Windows 11 Enterprise 23H2,
Browser: Chrome 127.0.6533.89
Storage: Dropbox

### PR DESCRIPTION
**Pull request by subdavis**
fixes #338 
fixes #349

### CODE REVIEW

File: scripts/manifest.ts [hunk 1]
```diff
@@ -75,12 +75,12 @@ const baseManifest: Manifest.WebExtensionManifest = {
...
 	return Object.assign({}, baseManifest, {
 		"manifest_version": 3,
-		"minimum_chrome_version": "88",
+		"minimum_chrome_version": "102",
 		"oauth2": {
 			// The Chrome identity client ID for Chrome ONLY
 			"client_id": "876467817034-al13p9m2bphgregs0rij76n1tumakcqr.apps.googleusercontent.com",
 			"scopes": [
-				"https://www.googleapis.com/auth/drive.readonly"
+				"https://www.googleapis.com/auth/drive.file"
```
Comment (subdavis) [inline scripts/manifest.ts:83]: cc #354 

I caused a regression here by reverting an earlier change to `drive.readonly` (the wrong permission).
